### ISSUE TITLE
Do not create shaded artifact which prevents dependency override.

### ISSUE THREAD

**Issue by khmarbaise** [tcurdt/jdependency#13]
Currently your project shades the whole depenencies in particular `org.ow2.*` which means a consuming project can not override the used version by newer ones in cases where errors etc. occur.

**Comment by tcurdt** [comment]
That's the exact idea of shading the dependencies. The library becomes a black box without transitive dependencies and the fixes have to be made by releasing the library. Overriding anything but minor releases of dependencies is a bad idea anyway. Which is why I am not really convinced it's worth maintaining another artifact. Not even sure how this would work with maven central.

Can you make a good case for it other than "I want to upgrade asm1 for java compatibility"?

Also see https://github.com/tcurdt/jdependency/issues/11

**Comment by khmarbaise** [comment]
Unfortunately it's not a black box cause you inherit the classes including the ones given inside the jar and furthermore the problem is if you have a issue with an older version of the library like ASM which is shaded you can't overwrite it in a simple manner (which is advantage of transitive dependencies). I'm aware of the problems based on minor versions etc. which would be my own responsibility ...but at the moment I'm trying to upgrade maven-shade-plugin (trying to make a new release) to newer versions of ASM based on JDK9 / JDK10 issues which is at the moment not possible...cause I can't overwrite the versions of ASM cause it's shaded inside of jdependency...

**Comment by tcurdt** [comment]
The classes should be shaded that means they have completely different class names.

  https://github.com/tcurdt/jdependency/blob/master/pom.xml#L143

Only inheritance would expose the rewritten package for `ASM`. The `jdependency` classes do not inherit from `ASM` only the internal `ASM` helper classes do that no one should use.

  https://github.com/tcurdt/jdependency/tree/master/src/main/java/org/vafer/jdependency/asm

That said I think we should mark/document them as such.

So inheritance should not be a problem.
It should be a blackbox or otherwise there is a bug.

Which of course means if we need a newer version of `ASM` we also need to make a new `jdependency` release. Which to me sounds like the right thing to do.

**Comment by khmarbaise** [comment]
Ah..haven't read the pom file carefully enough...It would be great If you could do a new release of jdependency...

**Comment by tcurdt** [comment]
Right now I am on vacation with little/bad internet activity. I try my best. Otherwise it might have to wait 2 weeks. Can you confirm that `master` is all you need for the new release, @khmarbaise?

**Comment by tcurdt** [comment]
@khmarbaise I am back in civilization. How about master and a release from it?

**Comment by tcurdt** [comment]
Just release 1.4. This closes #15 and includes #14
